
CREATE DATABASE IF NOT EXISTS spotweb;
GRANT ALL ON spotweb.* TO spotweb@localhost IDENTIFIED BY "spotweb";
FLUSH PRIVILEGES;
GRANT CREATE TEMPORARY TABLES ON spotweb.* TO spotweb@localhost IDENTIFIED BY "spotweb";
FLUSH PRIVILEGES;
ALTER DATABASE spotweb DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci
